# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:52
from __future__ import unicode_literals

import cakes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cake_type', models.CharField(choices=[(b'Birthday', b'Birthday'), (b'Marriage', b'Marriage'), (b'New year', b'New year'), (b'Congratulate', b'Congratulate'), (b'Surprise', b'Surprise'), (b'Anniversary', b'Anniversary'), (b'Valentines Day', b'Valentines Day'), (b'Party', b'Party'), (b'Special with Cakes', b'Special with Cakes'), (b'Send Gifts', b'Send Gifts'), (b'Propose', b'Propose')], max_length=25)),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=cakes.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('details', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=cakes.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField(null=True)),
                ('quantity', models.IntegerField()),
                ('cake_message', models.TextField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='cakes.Cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
