# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_auto_20170619_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_type',
            field=models.CharField(choices=[(b'Birthday', b'Birthday'), (b'Marriage', b'Marriage'), (b'New year', b'New year'), (b'Congratulate', b'Congratulate'), (b'Surprise', b'Surprise'), (b'Anniversary', b'Anniversary'), (b'Valentines Day', b'Valentines Day'), (b'Party', b'Party'), (b'Special with Cakes', b'Special with Cakes'), (b'Send Gifts', b'Send Gifts'), (b'Propose', b'Propose'), (b'Festivals', b'Festivals')], max_length=25),
        ),
    ]
