# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:04
from __future__ import unicode_literals

import cakes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_cake_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcake',
            name='phone',
            field=models.CharField(max_length=15, validators=[cakes.models.phone_validator]),
        ),
        migrations.AlterField(
            model_name='ordercake',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[cakes.models.phone_validator]),
        ),
    ]
