# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_auto_20170621_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercake',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
