# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_ordercake_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='flavour',
            field=models.CharField(choices=[(b'Vanila', b'Vanila'), (b'Whiteforest', b'Whiteforest'), (b'Blackforest', b'Blackforest'), (b'Choclate', b'Choclate'), (b'Butterscotch', b'Butterscotch'), (b'Mix Fruit', b'Mix Fruit'), (b'Pineapple', b'Pineapple'), (b'Strawberry', b'Strawberry'), (b'Ice Cream', b'Ice Cream'), (b'Mocha', b'Mocha'), (b'Blueberry', b'Blueberry')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.CharField(choices=[(b'1', b'1'), (b'1.5', b'1.5'), (b'2', b'2'), (b'2.5', b'2.5'), (b'3', b'3'), (b'3.5', b'3.5'), (b'4', b'4'), (b'4.5', b'4.5'), (b'5', b'5')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ordercake',
            name='flavour',
            field=models.CharField(choices=[(b'Vanila', b'Vanila'), (b'Whiteforest', b'Whiteforest'), (b'Blackforest', b'Blackforest'), (b'Choclate', b'Choclate'), (b'Butterscotch', b'Butterscotch'), (b'Mix Fruit', b'Mix Fruit'), (b'Pineapple', b'Pineapple'), (b'Strawberry', b'Strawberry'), (b'Ice Cream', b'Ice Cream'), (b'Mocha', b'Mocha'), (b'Blueberry', b'Blueberry')], max_length=15, null=True, verbose_name=b'Flavours'),
        ),
        migrations.AddField(
            model_name='ordercake',
            name='weight',
            field=models.CharField(choices=[(b'1', b'1'), (b'1.5', b'1.5'), (b'2', b'2'), (b'2.5', b'2.5'), (b'3', b'3'), (b'3.5', b'3.5'), (b'4', b'4'), (b'4.5', b'4.5'), (b'5', b'5')], max_length=5, null=True, verbose_name=b'weight(pounds):'),
        ),
    ]
