# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_auto_20170630_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercake',
            name='eggless',
            field=models.BooleanField(default=False),
        ),
    ]
